import io.get
import modules.InitModule
import modules.MooModule
import sx.blah.discord.api.ClientBuilder
import sx.blah.discord.api.IDiscordClient

/**
 * Created by David on 06/02/2017.
 * Main class. Autogenerated comment.
 *
 */

/**
 * Idea list:
 *
 *
 * -- News etc
 * - TODO github notifications
 * - TODO rss feed
 * - TODO HN & reddit digests
 * - TODO monitoring - servers etc
 *
 * -- Interactivity
 * + DONE fortune, respects etc (because we can)
 * - TODO taunts & replies
 * - TODO economy, slots, rolls
 *
 * -- Functionality
 * - TODO delete responses after set delay
 * - TODO purge messages by channels / users / time!
 *
 * -- Logistics
 * - TODO save module settings into separate YAML nodes
 * - TODO plain ol' user login (trivial)
 * - TODO gradle > maven!
 *
 * -- Large undertakings
 * - TODO musicbot
 * - TODO Fate RP integration (w/ dusanp/ServerFateSR)
 *
 *
 */

val client = login()

fun main(args: Array<String>) {

    client.dispatcher.registerListener(InitModule())
    client.dispatcher.registerListener(MooModule())

}

@Suppress("UNREACHABLE_CODE")
fun login():IDiscordClient{

    val builder = ClientBuilder()

    val token = get("api-token") as String?
    if(token == null || token == "") {
        throw Exception("Please specify an API token in config.yml!")
    }

    builder.withToken(token)

    try {
        println("Logging in with token: ${builder.token}")
        return builder.login()
    } catch (e: Exception){
        println("Error occurred while logging in!")
        e.printStackTrace()

    }

    /* IDEA complains whether this piece of unreachable
        code is here or not. Oh well */
    return null!!
}